config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cars#index_all"

  get '/my_cars', to: "cars#index"


  patch "/cars/:car_id/bookings/:id/accept(.:format) ", to: "bookings#accept", as: :accept_booking
  patch "/cars/:car_id/bookings/:id/reject(.:format)", to: "bookings#reject", as: :reject_booking

  resources :cars do
    resources :bookings, only: [:new, :create]
    # member do
    #   patch 'accept'
    #   patch 'reject'
    # end
    # member do
    #   patch 'accept'
    #   patch 'reject'
    # end
  end

  resources :bookings, only: [:index, :destroy, :show]
  # get "/cars/new", to: "pages#new"
  # get "/cars/:id", to: "pages#show", as: :show_cars
  # get "/cars", to: "pages#index"
  # post "/cars", to: "pages#create"

  # get "/cars/:user_id/:car_id/bookings/new", to: "bookings#new", as: :car_bookings
  # post "/cars/:user_id/:car_id/bookings", to: "bookings#create"
  # delete "/cars/:user_id/:car_id/bookings/:id", to: "bookings#destroy", as: :bookings
  # get "/cars/:user_id/:car_id/bookings/:id", to: "bookings#show", as: :show_booking
  # get "/cars/:user_id/bookings", to: "bookings#index", as: :display_bookings
  # patch "/cars/:user_id/bookings/:id/accept", to: "bookings#accept", as: :accept_booking
  # patch "/cars/:user_id/bookings/:id/decline", to: "bookings#decline", as: :decline_booking

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :image
  validates_presence_of :name, :year, :mileage, :description, :registration_number, :price_per_day
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :cars, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
    @current_user_bookings = current_user.bookings
    @user_car_bookings = Booking.joins(:car).where(cars: { user_id: current_user.id })
    # current_user.cars.each do |car|
    #   @user_car_bookings << car.bookings
    # end
    # @user_car_bookings = @user_car_bookings.flatten
    puts "DEBUG: @user_car_bookings=#{@user_car_bookings.inspect}"
  end

  def show
    @booking = Booking.find(params[:id])
    @car = @booking.car
    @owner = @booking.car.user
    @booker = @booking.user
  end

  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id])
    @booking.car = @car
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path, notice: 'Booking successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_path, notice: "Booking was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    if @booking.update!(status: 1)
      redirect_to bookings_path, notice: 'Booking accepted'
    else
      redirect_to bookings_path, notice: 'Booking could not be accepted - please try again'
    end
  end

  def reject
    @booking = Booking.find(params[:id])
    if @booking.update!(status: 2)
      redirect_to bookings_path, notice: 'Booking rejected'
    else
      redirect_to bookings_path, notice: 'Booking could not be rejected - please try again'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :car_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index]

  def index_all
    @cars_all = Car.all
  end

  def index
    @user_cars = current_user.cars
  end

  # def index_all
  #   @cars = Car.all
  # end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to @car, notice: "Car was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_path, notice: "Car was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def my_cars
    @cars.user = current_user
  end

  private

  def car_params
    params.require(:car).permit(:name, :year, :mileage, :description, :registration_number, :image, :price_per_day)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<div class="flex-container ">
  <div class="container my-5 booking-section">
    <h1>Bookings made by me:</h1>
    <p>View all bookings:</p>
    <% @current_user_bookings.each do |booking| %>
      <%= link_to booking_path(booking) do %>
        <div class="car-card card-product my-3">
          <% if booking.car.image.attached? %>
            <%= image_tag booking.car.image, class: 'img-fluid', alt: 'Car Image' %>
          <% else %>
            <p>No image available</p>
          <% end %>
          <h3> <%= booking.car.name%> </h3>
          <p> <%= "From: #{booking.start_date.strftime('%a %d %b %Y')}"%></p>
          <p> <%= "To: #{booking.end_date.strftime('%a %d %b %Y')} " %></p>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="container my-5  booking-section">
    <h1>Bookings made for my cars:</h1>
    <p>View all bookings:</p>
    <% @user_car_bookings.each do |booking| %>
      <%= link_to booking_path(booking) do %>
        <div class="car-card card-product my-3">
          <% if booking.car.image.attached? %>
            <%= image_tag booking.car.image, class: 'img-fluid', alt: 'Car Image' %>
          <% else %>
            <p>No image available</p>
          <% end %>
          <h2> <%= booking.car.name%> </h2>
          <p> <%= "From: #{booking.start_date.strftime('%a %d %b %Y')}"%></p>
          <p> <%= "To: #{booking.end_date.strftime('%a %d %b %Y')} " %></p>
        </div>
        <div class="container" id="accept-reject-buttons">
          <!-- Display booking details -->
          <p class="d-inline">STATUS: <%= booking.status.upcase %></p>
          <br>
          <% unless booking.status == "accepted" %>
            <%= link_to 'Accept', accept_booking_path(booking.car, booking), data: {turbo_method: :patch}, class: 'btn btn-success' %>
            <%= link_to 'Reject', reject_booking_path(booking.car, booking), data: {turbo_method: :patch}, class: 'btn btn-danger' %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new booking for a <%= @car.name %></h3>
        <%= simple_form_for [@car, @booking] do |f| %>
          <%= f.input :start_date, placeholder: 'From' %>
          <%= f.input :end_date, placeholder: 'From' %>
          <i class="fa fa-paper-plane"><%= f.submit%></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container my-4">
  <%# <h1><%= "Hello, #{@user.first_name}, here are the details for your listing:" %>
  <%# </h1> %>
  <div class="container mt-2">
    <div class="car-card card-product my-3 booking-section width:70% ">
      <h2><%= "Hello there, #{current_user.first_name}" %></h2>
      <p><%= "Your booking for #{@car.name} begins on #{@booking.start_date.strftime('%a %d %b %Y')} and will end on #{@booking.end_date.strftime('%a %d %b %Y')} ." %></p>
      <p><%=" The total price per day for this booking is #{@booking.price_per_day} EUR"%></p>
      <% if @booking.car.image.attached? %>
          <%= image_tag @booking.car.image, class: 'img-fluid', alt: 'Car Image' %>
      <% else %>
          <p>No image available</p>
      <% end %>
    </div>
  <div class="mt-2">
     <%= link_to "Back to bookings", bookings_path(current_user), class:"btn btn-info"  %>
     <%= button_to "Delete booking", @booking, method: :delete, class:"btn btn-danger" %>
  </div>
</div>

app/views/cars/index.html.erb
<div class="container">
  <h1>My Cars</h1>
  <% if @user_cars.any? %>
    <div class="grid-container">
      <% @user_cars.each do |car| %>
        <div class="car-card">
        <%= link_to car_path(car) do %>
          <% if car.image.present? %>
            <%= cl_image_tag car.image.key,class: "car-image", alt: "Car Image" %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dwft4wv8p/image/upload/v1700750938/Car_Junction_Animated_Logo_resized_vnxmkc.png" %>
          <% end %>
            <h3><strong><%= car.name %> (<%= car.year %>)</strong></h3>
            <div class="card-price">
              <p><i class="fa-solid fa-money-check-dollar mr-5"></i><%= car.price_per_day %> / day</p>
              <p><i class="fa-solid fa-gauge"></i><%= car.mileage %> </p>
            </div>
            <div class="card-description">

              <p><%= car.description %></p>
            </div>
              <%# <%= button_to "Delete car", car, method: :delete, class:"btn btn-danger"%>
              <%= link_to "Delete car", car_path(car), data: {turbo_method: :delete}, class: "btn btn-danger" %>
              <%= link_to "My Bookings", bookings_path, class: "btn btn-primary" %>
            </div>
        <% end %>
      <% end %>
        </div>
  <% else %>
    <p>No cars found.</p>
  <% end %>
</div>

app/views/cars/index_all.html.erb
<div class="container">
  <h1><strong>Car Junction</strong></h1>
  <p>Drive the Experience, Rent the Journey</p>
  <div class="grid-container">
    <% @cars_all.each do |car| %>
      <%= link_to car_path(car) do %>
        <div class="car-card">
          <% if car.image.present? %>
            <%= cl_image_tag car.image.key,class: "car-image", alt: "Car Image" %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dwft4wv8p/image/upload/v1700750938/Car_Junction_Animated_Logo_resized_vnxmkc.png" %>
          <% end %>
          <h3><strong><%= car.name %> (<%= car.year %>)</strong></h3>
          <div class="card-price">
            <p><i class="fa-solid fa-money-check-dollar mr-5"></i><%= car.price_per_day %> / day</p>
            <p><i class="fa-solid fa-gauge"></i><%= car.mileage %> </p>
          </div>
          <div class="card-description">

            <p><%= car.description %></p>
          </div>
        </div>
     <% end %>
    <% end %>
    </div>
</div>

app/views/cars/new.html.erb
<div class="container mt-4 mb-4">
  <div class="card-body text-center">
    <h1 >Upload your car</h1>
  </div>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-body">
          <%= form_with(model: @car, local: true, html: { multipart: true }) do |form| %>
            <div class="mb-3">
              <%= form.label :name, class: "form-label" %>
              <%= form.text_field :name, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :year, class: "form-label" %>
              <%= form.select :year, (Date.today.year - 50..Date.today.year).to_a.reverse, { include_blank: 'Select year' }, class: "form-select" %>
            </div>

            <div class="mb-3">
              <%= form.label :mileage, class: "form-label" %>
              <div class="input-group">
                <%= form.text_field :mileage, class: "form-control" %>
              </div>
            </div>

            <div class="mb-3">
              <%= form.label :description, class: "form-label" %>
              <%= form.text_area :description, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :registration_number, class: "form-label" %>
              <%= form.text_field :registration_number, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :price_per_day, class: "form-label" %>
              <%= form.text_field :price_per_day, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :image, class: 'form-label' %>
              <%= form.file_field :image, class: 'form-control' %>
            </div>

              <%= form.submit "Upload Car", class: "btn btn-success" %>


          <% end %>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container my-5">
  <div class="car-card my-3">
        <% if @car.image.present? %>
          <%= cl_image_tag @car.image.key,class: "car-image", alt: "Car Image" %>
        <% else %>
          <p>No image available</p>
        <% end %>
  </div>
  <h1><%= @car.name %></h1>
  <div class="car-card my-3">
  <%= link_to "Book car", new_car_booking_path(@car), class:"btn btn-success"  %>
</div>
<div class="car-card my-3">
  <%= link_to "Back to Cars", root_path, class:"btn btn-info" %>
</div>

<%# <div class="car-card my-3">
  <%= button_to "Delete car", @booking, method: :delete, class:"btn btn-danger"%>
</div> 

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="https://www.motownautowholesale.com.au/wp-content/uploads/2021/10/Motown-Auto-Muscle-Cars_LogoRGB.png">
    <title>CarJunction</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
    </p>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="https://github.com/BF20190401"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Car Junction
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dwft4wv8p/image/upload/v1700750938/Car_Junction_Animated_Logo_resized_vnxmkc.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <li class="nav-item active" >
          <%= link_to "My Cars", my_cars_path,  class: "nav-link" %>
        </li>
        <li class="nav-item active" >
           <%= link_to "List A Car", new_car_path, class: "nav-link" %>
        </li>
        <li class="nav-item active" >
        <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
        </li>

          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://tfrm.org/wp-content/uploads/2021/04/Untitled-design.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>